import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/animations.css";
import "antd/dist/reset.css";
import AppProvider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EZWind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="blur-[300px] bg-[#924dff] rounded-full w-[395px] h-[390px] absolute top-[-195px] left-[50%] right-[50%] transform -translate-x-1/2" />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
