export enum queryKeys {
  USER_SESSION = "user-session",
  GET_LIST_PRODUCT_DATA = "get-list-product-data",
  GET_CUSTOMER_LIST_PRODUCT_DATA = "get-customer-list-product-data",
  DET_DETAIL_PRODUCT_DATA = "get-detail-product-data",
  GET_INVENTORIES_DATA = "get-inventories-data",
  GET_INVENTORY_DATA = "get-inventory_data",
  GET_PRODUCT_INVENTORY_LOG = "get-product-inventory-log",
  GET_STOCK_HISTORY = "get-stock-history",
  GET_STOCK_HISTORY_DETAIL = "get-stock-history-detail",
  GET_BRANDS = "get-brands",
  GET_RAMS = "get-rams",
  GET_PROCESSORS = "get-processors",
  GET_STORAGES = "get-storages",
  GET_GPUS = "get-gpus",
  SEARCH_PRODUCTS = "search-products",
  GET_PRODUCTS_IN_CART = "get-products-in-cart",
  GET_RECOMMENDATION = "get-recommendation",
  GET_CHECKOUT_SESSION = "get-checkout-session",
}
